Repository boocam-project/FastTime-front, pull requests merged in 2023-10, with the labels that each got.

#17 에디터 컴포넌트 추가
  index.html
  package-lock.json
  package.json
  src/App.tsx
  src/components/atoms/input/InputIcon.tsx
  src/components/atoms/input/index.tsx
  src/components/atoms/input/input.module.scss
  src/components/editor/index.tsx
  src/components/editor/styles.scss
  src/components/form/index.tsx
  src/styles/base/_reset.scss
Labels: feature

#19 태그 버튼 구조 추가 및 수정
  src/components/atoms/button/button.module.scss
  src/components/atoms/button/index.tsx
Labels: feature

#20 푸터 제작 및 폰트 사이즈 정의
  .eslintrc.cjs
  src/components/layout/footer/footer.module.scss
  src/components/layout/footer/index.tsx
  src/data/teamMembersData.ts
  src/styles/abstracts/_variables.scss
Labels: feature

#21 에디터 사진 기능 추가 및 파이어베이스 연결
  .gitignore
  cors.json
  env.d.ts
  package-lock.json
  package.json
  src/components/editor/MenuBar.tsx
  src/components/editor/Title.tsx
  src/components/editor/index.tsx
  src/components/editor/styles.scss
  src/hooks/useBlobUrl.ts
  src/libs/firebase.ts
  src/styles/abstracts/_variables.scss
  tsconfig.json
Labels: feature

#23 토글 바 작업 완료 및 헤더 진행중
  package-lock.json
  package.json
  src/App.tsx
  src/components/editor/index.tsx
  src/components/layout/header/header.module.scss
  src/components/layout/header/index.tsx
  src/components/layout/toggleBar/index.tsx
  src/components/layout/toggleBar/toggleBar.module.scss
Labels: feature

#24 헤더 작업 완료
  src/components/layout/header/header.module.scss
  src/components/layout/header/index.tsx
  src/components/layout/toggleBar/index.tsx
  src/components/layout/toggleBar/toggleBar.module.scss
  src/styles/abstracts/_mixins.scss
  src/styles/abstracts/_variables.scss
Labels: feature

#25 버튼 스타일 및 사이즈 수정
  src/components/atoms/button/button.module.scss
  src/components/atoms/button/index.tsx
Labels: fix

#26 절대 경로 수정 및 게시판 페이지 디자인
  src/App.tsx
  src/components/community/ArticleItem.tsx
  src/components/community/ArticleList.tsx
  src/components/community/article.module.scss
  src/components/community/articles.ts
  src/components/editor/index.tsx
  src/pages/community/index.tsx
  src/styles/abstracts/_variables.scss
  tsconfig.json
  vite.config.ts
Labels: feature

#27 에디터 구조 및 디자인 수정
  src/components/atoms/input/index.tsx
  src/components/editor/MenuBar.tsx
  src/components/editor/index.tsx
  src/components/editor/styles.scss
  src/hooks/useBlobUrl.ts
  src/hooks/useImageConvert.ts
  src/styles/abstracts/_variables.scss
  src/styles/base/_reset.scss
Labels: refactoring

#28 에디터 버튼 디자인 수정 및 CSS 중복 import 제거
  src/App.tsx
  src/components/atoms/button/button.module.scss
  src/components/atoms/input/input.module.scss
  src/components/community/article.module.scss
  src/components/editor/index.tsx
  src/components/editor/styles.scss
  vite.config.ts
Labels: refactoring

#32 게시글 페이지 제작
  src/components/community/ArticleDetail.tsx
  src/components/editor/index.tsx
Labels: feature

#30 회원가입 페이지 추가와 푸터 수정
  src/App.tsx
  src/components/layout/footer/index.tsx
  src/components/signUp/SignUpForm.tsx
  src/components/signUp/index.tsx
  src/components/signUp/signUp.module.scss
Labels: feature

#31 로그인 api 연결 및 baseURL 설정
  src/api/client.ts
  src/components/signIn/SignInForm.tsx
  src/components/signIn/index.tsx
Labels: feature

#34 Feature/마이페이지 ui 작업
  public/data/board.json
  public/data/coments.json
  public/data/mypage.json
  src/App.tsx
  src/components/layout/toggleBar/toggleBar.module.scss
  src/pages/myBoard/index.tsx
  src/pages/myBoard/myBoard.module.scss
  src/pages/myComents/index.tsx
  src/pages/myComents/myComents.module.scss
  src/pages/myPage/index.tsx
  src/pages/myPage/myPage.module.scss
  src/routes/router.tsx
Labels: feature

#35 이메일 인증 관련 코드 추가
  src/App.tsx
  src/components/signUp/SignUpForm.tsx
  src/components/signUp/index.tsx
  src/components/signUp/signUp.module.scss
Labels: feature

#36 게시글 및 댓글 불러오기 기능 추가
  src/App.tsx
  src/components/comment/Comment.tsx
  src/components/comment/CommentBox.tsx
  src/components/comment/CommentList.tsx
  src/components/comment/index.module.scss
  src/components/community/ArticleDetail.tsx
  src/components/community/ArticleItem.tsx
  src/components/community/article.module.scss
  src/components/community/convertNodeToHtml.ts
  src/components/editor/index.tsx
  src/components/layout/header/index.tsx
  src/data/comment.ts
  src/routes/router.tsx
  src/styles/abstracts/_variables.scss
Labels: feature

#37 Footer 스타일 수정, 구글폼 삽입
  src/components/layout/footer/footer.module.scss
  src/components/layout/footer/index.tsx
Labels: feature

#38 댓글 등록, 수정, 삭제 및 API 커스텀 훅 제작
  src/api/client.ts
  src/components/comment/CommentBox.tsx
  src/components/comment/CommentInput.tsx
  src/components/comment/CommentItem.tsx
  src/components/comment/CommentList.tsx
  src/components/comment/formatTime.ts
  src/components/comment/index.module.scss
  src/components/comment/index.tsx
  src/components/community/ArticleDetail.tsx
  src/components/community/ArticleItem.tsx
  src/components/community/ArticleList.tsx
  src/components/community/article.module.scss
  src/components/community/articles.ts
  src/components/editor/index.tsx
  src/components/signIn/SignInForm.tsx
  src/data/comment.ts
  src/hooks/useData.ts
  src/routes/router.tsx
  vite.config.ts
Labels: fix, feature

#40 로그인한 상태 코드 분리 , 상태관리에 로그인 정보 추가
  src/components/signIn/SignInForm.tsx
  src/main.tsx
  src/pages/myBoard/index.tsx
  src/pages/myComents/index.tsx
  src/pages/myPage/index.tsx
  src/store/store.tsx
Labels: fix

#41 새로운 댓글 작성 시 optimistic UI 적용
  .env.development
  .env.production
  src/api/client.ts
  src/components/comment/CommentBox.tsx
  src/components/comment/CommentEdit.tsx
  src/components/comment/CommentInput.tsx
  src/components/comment/CommentList.tsx
  src/components/comment/edit.module.scss
  src/components/comment/index.module.scss
  src/components/editor/index.tsx
  src/components/editor/styles.scss
  src/hooks/mutations.ts
  vite.config.ts
Labels: feature

#58 게시글 및 댓글 UI 최적화 및 변경
  package-lock.json
  package.json
  src/components/comment/CommentEdit.tsx
  src/components/comment/CommentInput.tsx
  src/components/comment/CommentList.tsx
  src/components/comment/CommentSkeletons.tsx
  src/components/comment/formatTime.ts
  src/components/comment/index.module.scss
  src/components/comment/organizeComments.ts
  src/components/comment/skeleton.module.scss
  src/components/community/ArticleDetail.tsx
  src/components/community/ArticleList.tsx
  src/components/community/ArticleSkeletons.tsx
  src/components/community/changeTimeFormat.ts
  src/components/community/convertNodeToHtml.ts
  src/components/community/details.module.scss
  src/components/community/index.module.scss
  src/components/community/skeletons.module.scss
  src/components/editor/index.tsx
  src/components/skeletons/index.module.scss
  src/components/skeletons/index.tsx
  src/constants/constants.ts
  src/hooks/mutations.ts
  src/hooks/useMutations.ts
  src/main.tsx
  src/pages/myBoard/index.tsx
  src/pages/myComents/index.tsx
  src/store/store.ts
Labels: feature

#60 관리자 로그인 페이지 구현
  src/pages/adminLogin/admin.module.scss
  src/pages/adminLogin/index.tsx
Labels: feature

#61 관리자 신고게시물 목록 페이지 , 신고 게시물 상세페이지
  src/components/layout/footer/footer.module.scss
  src/pages/AdminBoardDetail/adminBoardDetail.module.scss
  src/pages/AdminBoardDetail/index.tsx
  src/pages/adminBoard/adminBoard.module.scss
  src/pages/adminBoard/index.tsx
  src/pages/adminLogin/index.tsx
  src/routes/router.tsx
Labels: feature

#62 회원 가입 이메일 인증 로직 추가
  src/components/signUp/SignUpForm.tsx
  src/components/signUp/signUp.module.scss
Labels: feature

#66 관리자 로그아웃 구현
  src/components/layout/footer/footer.module.scss
  src/components/layout/header/index.tsx
Labels: feature

#68 회원탈퇴 기능구현 완료
  src/pages/adminBoard/adminBoard.module.scss
  src/pages/adminLogin/index.tsx
  src/pages/myBoard/index.tsx
  src/pages/myComents/index.tsx
  src/pages/myPage/index.tsx
  src/pages/myPage/myPage.module.scss
Labels: feature

#70 댓글 삭제 optimistic update 적용
  src/components/comment/CommentEdit.tsx
  src/components/comment/CommentInput.tsx
  src/components/comment/CommentList.tsx
  src/components/comment/index.module.scss
  src/components/community/ArticleDetail.tsx
  src/components/community/details.module.scss
  src/constants/constants.ts
  src/hooks/useArticles.ts
  src/hooks/useCommentMutations.ts
Labels: feature

#72 useModal, modal eslint 경고 해결
  src/components/atoms/modal/index.tsx
  src/components/community/ArticleDetail.tsx
  src/components/community/ArticleList.tsx
  src/hooks/useModal.ts
Labels: fix

#69 lint-check.yml 작성
  .github/workflows/lint-check.yml
Labels: feature

#71 댓글 목록 더보기 기능 구현
  src/components/atoms/modal/index.tsx
  src/components/atoms/modal/modal.module.scss
  src/components/layout/header/header.module.scss
  src/components/layout/header/index.tsx
  src/pages/myBoard/index.tsx
  src/pages/myBoard/myBoard.module.scss
  src/pages/myComents/index.tsx
  src/pages/myComments/index.tsx
  src/pages/myComments/myComments.module.scss
  src/pages/myPage/index.tsx
  src/pages/myPage/myPage.module.scss
Labels: feature

#77 헤더 스타일 수정 , 댓글 스타일 수정, 모달 닫기 기능 추가 , 더보기 , 초기화 기능구현 , 불필요한 코드 제거 ...
  src/components/atoms/modal/index.tsx
  src/components/layout/header/header.module.scss
  src/hooks/useModal.ts
  src/pages/AdminBoardDetail/index.tsx
  src/pages/adminBoard/index.tsx
  src/pages/myBoard/index.tsx
  src/pages/myBoard/myBoard.module.scss
  src/pages/myComments/index.tsx
  src/pages/myComments/myComments.module.scss
Labels: feature

#76 게시글 무한 스크롤 구현 및 댓글 작성 시 로그인 여부 확인
  .gitignore
  src/api/articleService.ts
  src/components/comment/CommentList.tsx
  src/components/community/ArticleDetail.tsx
  src/components/community/ArticleList.tsx
  src/components/community/index.module.scss
  src/hooks/useArticles.ts
  src/hooks/useCommentMutations.ts
  src/hooks/useLikeMutations.ts
Labels: feature

#79 Footer 수정, logo.svg로 로고 적용, sessionManager.ts 생성, 기능 없는 nav에 alert 창 추가
  src/assets/logo.svg
  src/components/layout/footer/footer.module.scss
  src/components/layout/header/header.module.scss
  src/components/layout/header/index.tsx
  src/components/signIn/sessionManager.ts
Labels: feature

#81 Fix: 내가 쓴글 , 댓글 버튼위치 이동
  src/pages/myBoard/index.tsx
  src/pages/myBoard/myBoard.module.scss
  src/pages/myComments/index.tsx
  src/pages/myComments/myComments.module.scss
Labels: fix

#82 댓글 수 보여주기 및 403 에러 axios interceptor 추가
  src/api/client.ts
  src/api/interceptors.ts
  src/components/community/ArticleDetail.tsx
  src/components/community/ArticleList.tsx
  src/components/community/index.module.scss
  src/constants/constants.ts
  src/hooks/useArticles.ts
  src/hooks/useCommentMutations.ts
  src/hooks/useLikeMutations.ts
  src/main.tsx
Labels: feature

#85 서버 baseURL 변경 및 게시글 익명 노출
  .github/workflows/preview.yml
  src/api/client.ts
  src/components/community/ArticleDetail.tsx
  vite.config.ts
Labels: feature

#86 게시글 페이지 관련 에러 수정
  index.html
  public/logo.svg
  src/components/comment/CommentInput.tsx
  src/components/comment/CommentList.tsx
  src/components/editor/index.tsx
  vercel.json
Labels: fix

#89 게시글 좋아요 optimistic updates 적용
  src/api/articleService.ts
  src/components/community/ArticleDetail.tsx
  src/hooks/useArticles.ts
  src/hooks/useLikeMutations.ts
Labels: feature

#90 헤더 UI 수정
  src/components/atoms/modal/index.tsx
  src/components/layout/header/header.module.scss
  src/components/layout/header/index.module.scss
  src/components/layout/header/index.tsx
  src/components/layout/toggleBar/index.tsx
  src/components/layout/toggleBar/toggleBar.module.scss
  src/components/signIn/SignInForm.tsx
  src/store/store.ts
  src/styles/abstracts/_variables.scss
Labels: fix
